Adding hydra test for model hot-reloading
o3de/o3de-atomtest pull request #78
Opened 2021-09-24 21:57 UTC by amzn-tommy

Signed-off-by: amzn-tommy <waltont@amazon.com>

2021-09-27 18:54 UTC, smurly commented on Gem/PythonTests/Automated/test_suites/periodic/ModelHotReloading_test_case.py
> +    displayVertexColorPath = 'testdata/objects/modelhotreload/displayvertexcolor.azmaterial'
use os.path.join to match eventual AutomatedTesting style. I'm not sure there's any platform specific pathing to be concerned about but tests will need to eventually run on both windows and linux

2021-09-27 18:54 UTC, smurly commented on Gem/PythonTests/Automated/test_suites/periodic/ModelHotReloading_test_case.py
> +    displayVertexColorAssetId = azlmbr.asset.AssetCatalogRequestBus(azlmbr.bus.Broadcast, 'GetAssetIdByPath', displayVertexColorPath, azlmbr.math.Uuid(), False)
hydra_editor_utils.get_asset_by_path(path) hides most of this bus call for the same result

2021-09-27 18:54 UTC, smurly commented on Gem/PythonTests/Automated/test_suites/periodic/ModelHotReloading_test_case.py
> +    modelId = azlmbr.asset.AssetId_CreateString("{66ADF6FF-3CA4-51F6-9681-5697D4A29F56}:10241ecb")
will this static uuid be unchanging when shifted for AutomatedTesting or user installs.
we set the mesh asset to this ID before the file exists. how is the asset controlled to have this ID after creation/processing?

2021-09-27 18:54 UTC, smurly commented on Gem/PythonTests/Automated/test_suites/periodic/ModelHotReloading_test_case.py
> +    # Use the presence of a single material slot in the material component to validate the m
to validate the m
material?

2021-09-27 18:54 UTC, smurly commented on Gem/PythonTests/Automated/test_suites/periodic/ModelHotReloading_test_case.py
> +        general.log("  AssignementId (slotId:lod): {0}".format(assignmentId.ToString()))
f-string is generally preferred to .format 
```suggestion
        general.log(f"  AssignementId (slotId:lod): {assignmentId}")
```

2021-09-27 18:54 UTC, smurly commented on Gem/PythonTests/Automated/test_suites/periodic/ModelHotReloading_test_case.py
> +    # Helper function useful while writing/modifying the test that will output the available materials slots
use docstring triple quotes

2021-09-27 18:54 UTC, smurly commented on Gem/PythonTests/Automated/test_suites/periodic/ModelHotReloading_test_case.py
> +    # keep track of whether or not each materialLabel for each lod is found
docstring to define params and return type

2021-09-27 18:54 UTC, smurly commented on Gem/PythonTests/Automated/test_suites/periodic/ModelHotReloading_test_case.py
> +def copy_file(srcPath, dstPath):
this seems like it should be in a common util file.

2021-09-28 23:18 UTC, jromnoa commented
For this PR it's fine to merge to AtomTest for now, but it will need converting to AutomatedTesting following our new parallel test approach. I will let @NeilGitGud know for the new test update tickets

2021-09-29 00:41 UTC, jromnoa requested changes

2021-09-29 00:41 UTC, jromnoa commented on Gem/PythonTests/Automated/test_suites/periodic/ModelHotReloading_test_case.py
> +            waitCondition = partial(self.model_is_ready_predicate)
why does this have to be `partial()`? there's only `self` inheritance for parameters and so no custom function signature or interface is needed to make this call.

couldn't we just remove `model_is_ready_predicate()` altogether for the `waitCondition` variable and do `lambda: self.isModelReady` and plug that in for the callback value on the `wait_for_condition()` line below (nitpick sidenote: `wait_condition` is more pythonic snake_cased and not camelCased over `waitCondition`).

in general, using `partial()` makes tracking function interfaces and signatures difficult when it doesn't have the same expected parameters called with it (or default values for parameters can be used as well to get around this) - we should avoid using it if possible

2021-09-29 00:41 UTC, jromnoa commented on Gem/PythonTests/Automated/test_suites/periodic/ModelHotReloading_test_case.py
> +    12. Closes the Editor and the test ends.
should be 16 not 12

2021-09-29 00:41 UTC, jromnoa commented on Gem/PythonTests/Automated/test_suites/periodic/ModelHotReloading_test_case.py
> +    # Set mesh asset 'testdata/objects/modelhotreload/hotreload.azmodel'
might be best to not explicitly name this here in case file names change this becomes a new location to update / can be missed - i would just put "Sets correct mesh asset."

2021-09-29 00:41 UTC, jromnoa commented on Gem/PythonTests/Automated/test_suites/periodic/ModelHotReloading_test.py
> +            "OnModelReady never happened",
would it be better to have a log line for each type of `"OnModelReady never happened"` that failed? this makes parsing failures easier i.e these unexpected_lines strings added:
```
"OnModelReady never happened - vertexcolor.fbx"
"OnModelReady never happened - novertexcolor.fbx"
"OnModelReady never happened - multi-mat_mesh-groups_1m_cubes.fbx"
# etc. for each specific one, otherwise debugging is much more difficult
```

2021-09-29 00:41 UTC, jromnoa commented on Gem/PythonTests/Automated/test_suites/periodic/ModelHotReloading_test_case.py
> +                general.log("  lod: {0}".format(assignmentId.lodIndex))
can use f strings over `.format()` i.e.
```
general.log(f"  lod: {assignmentId.lodIndex}")
```

2021-09-29 00:41 UTC, jromnoa commented on Gem/PythonTests/Automated/test_suites/periodic/ModelHotReloading_test_case.py
> +                    general.log("  lod: {0} slot label: {1}".format(assignmentId.lodIndex, slotLabel))
use f strings over `format()`

2021-09-29 00:41 UTC, jromnoa commented on Gem/PythonTests/Automated/test_suites/periodic/ModelHotReloading_test_case.py
> +                general.log("  lod: {0} slot label: {1}".format(assignmentId.lodIndex, slotLabel))
use f strings over `format()`

2021-09-29 00:41 UTC, jromnoa commented on Gem/PythonTests/Automated/test_suites/periodic/ModelHotReloading_test_case.py
> +TESTDATA_ASSET_PATH = os.path.join(
why do we define this constant? its only used in the `copy_file()` function you made and i don't see it referenced anywhere else - would be better to keep this value closer to the code calling it if nothing else is using this constant (at least not that i can see)

2021-09-29 00:41 UTC, jromnoa commented on Gem/PythonTests/Automated/test_suites/periodic/ModelHotReloading_test_case.py
> +    modelMaterialOverrideLod = 18446744073709551615
is this always the same? it looks oddly specific / potential hard-coded trap, just calling it out cause im not 100% sure and it might be fine

2021-09-29 00:41 UTC, jromnoa commented on Gem/PythonTests/Automated/test_suites/periodic/ModelHotReloading_test_case.py
> +    materialLabelDict = {modelMaterialOverrideLod:lodMaterialList, 0:lodMaterialList}
nitpick: the way this `dict` is formatted is very confusing, can you split it like this?
```
# I am going to use snake_casing cause typing python in camelCase bugs me :P
material_label_dict = {
    model_material_override_lod: lod_material_list,
    0: lod_material_list,  # we should avoid using numbers for dict index values, strings are preferred - numbers are generally used by lists for indices and not dicts, dicts generally use strings
    "new_index": "new_value",  # I added this to show each line = new element in dict.
}
```
same for all other dicts, they are hard to read because lack of spaces and formatting

2021-09-29 00:41 UTC, jromnoa commented on Gem/PythonTests/Automated/test_suites/periodic/ModelHotReloading_test_case.py
> +    materialLabelDict = {modelMaterialOverrideLod:["lambert0", "lambert3", "lambert4", "lambert5", "lambert6"], 0:["lambert0"], 1:["lambert3"], 2:["lambert4"], 3:["lambert5"], 4:["lambert6"]}
please re-format this `dict` to be more readable - see notes above on line 156

2021-09-29 00:41 UTC, jromnoa commented on Gem/PythonTests/Automated/test_suites/periodic/ModelHotReloading_test_case.py
> +    materialLabelDict = {modelMaterialOverrideLod:lodMaterialList, 0:lodMaterialList}
nitpick: also remember to add trailing commas on the last element/item in lists and dicts

2021-09-29 00:41 UTC, jromnoa commented on Gem/PythonTests/Automated/test_suites/periodic/ModelHotReloading_test_case.py
> +    materialLabelDict = {modelMaterialOverrideLod:lodMaterialList, 0:lodMaterialList}
please re-format this dict to be more readable - see notes above on line 156

2021-09-29 00:41 UTC, jromnoa commented on Gem/PythonTests/Automated/test_suites/periodic/ModelHotReloading_test_case.py
> +        general.log("  SlotLabel: {0}".format(slotLabel))
use f strings over `.format()`

2021-09-29 00:41 UTC, jromnoa commented on Gem/PythonTests/Automated/test_suites/periodic/ModelHotReloading_test_case.py
> +    except BaseException as error:
`except Exception as error: ` works better as `BaseException` catches things like `KeyboardInterrupt` which we generally don't care for in tests

2021-09-29 23:29 UTC, amzn-tommy reviewed
For everything that I've said I'll follow up on when porting to AutomatedTesting, I've added a comment to the task I'm using to track that work so that I don't forget.

2021-09-29 23:29 UTC, amzn-tommy commented on Gem/PythonTests/Automated/test_suites/periodic/ModelHotReloading_test_case.py
> +    materialLabelDict = {modelMaterialOverrideLod:lodMaterialList, 0:lodMaterialList}
reformatted. I use a number as the key instead of a string, because that's what's used as the key for a MaterialAssignmentMap. I'm not using a list because the model_material_override_lod index is 18446744073709551615, so I don't want a list with that many elements.

2021-09-29 23:29 UTC, amzn-tommy commented on Gem/PythonTests/Automated/test_suites/periodic/ModelHotReloading_test_case.py
> +    materialLabelDict = {modelMaterialOverrideLod:["lambert0", "lambert3", "lambert4", "lambert5", "lambert6"], 0:["lambert0"], 1:["lambert3"], 2:["lambert4"], 3:["lambert5"], 4:["lambert6"]}
reformatted.

2021-09-29 23:29 UTC, amzn-tommy commented on Gem/PythonTests/Automated/test_suites/periodic/ModelHotReloading_test_case.py
> +    materialLabelDict = {modelMaterialOverrideLod:lodMaterialList, 0:lodMaterialList}
reformatted.

2021-09-29 23:29 UTC, amzn-tommy commented on Gem/PythonTests/Automated/test_suites/periodic/ModelHotReloading_test_case.py
> +    # Use the presence of a single material slot in the material component to validate the m
model reloaded. Fixed.

2021-09-29 23:29 UTC, amzn-tommy commented on Gem/PythonTests/Automated/test_suites/periodic/ModelHotReloading_test_case.py
> +    # Helper function useful while writing/modifying the test that will output the available materials slots
done.

2021-09-29 23:29 UTC, amzn-tommy commented on Gem/PythonTests/Automated/test_suites/periodic/ModelHotReloading_test_case.py
> +        general.log("  AssignementId (slotId:lod): {0}".format(assignmentId.ToString()))
I have to use assignmentId.ToString() here, but that works. Did not know about f-string, it is way better!

2021-09-29 23:29 UTC, amzn-tommy commented on Gem/PythonTests/Automated/test_suites/periodic/ModelHotReloading_test_case.py
> +        general.log("  SlotLabel: {0}".format(slotLabel))
done

2021-09-29 23:29 UTC, amzn-tommy commented on Gem/PythonTests/Automated/test_suites/periodic/ModelHotReloading_test_case.py
> +                general.log("  lod: {0}".format(assignmentId.lodIndex))
done

2021-09-29 23:29 UTC, amzn-tommy commented on Gem/PythonTests/Automated/test_suites/periodic/ModelHotReloading_test_case.py
> +                    general.log("  lod: {0} slot label: {1}".format(assignmentId.lodIndex, slotLabel))
done

2021-09-29 23:29 UTC, amzn-tommy commented on Gem/PythonTests/Automated/test_suites/periodic/ModelHotReloading_test_case.py
> +                general.log("  lod: {0} slot label: {1}".format(assignmentId.lodIndex, slotLabel))
done

2021-09-29 23:29 UTC, amzn-tommy commented on Gem/PythonTests/Automated/test_suites/periodic/ModelHotReloading_test_case.py
> +def copy_file(srcPath, dstPath):
I'll look into it when moving to Automated testing

2021-09-29 23:29 UTC, amzn-tommy commented on Gem/PythonTests/Automated/test_suites/periodic/ModelHotReloading_test_case.py
> +    except BaseException as error:
Done.

2021-09-29 23:29 UTC, amzn-tommy commented on Gem/PythonTests/Automated/test_suites/periodic/ModelHotReloading_test_case.py
> +    # keep track of whether or not each materialLabel for each lod is found
Done.

2021-09-29 23:46 UTC, smurly approved these changes

2021-09-29 23:46 UTC, smurly commented on Gem/PythonTests/Automated/test_suites/periodic/ModelHotReloading_test_case.py
> +    -- reload to different model (sphere5_lods)
double dash at the beginning. not really an issue just formatting

2021-09-30 01:39 UTC, jromnoa approved these changes

2021-10-05 16:59 UTC, merged