updating material alpha
o3de/o3de-atomtest pull request #84
Opened 2021-12-03 19:23 UTC by mrieggeramzn

Updating decal materials with better settings so that they are visible in the Material Editor

checked ASV to make sure decal asv test still runs ok

ATOM-15909

Signed-off-by: mrieggeramzn <mriegger@amazon.com>

2021-12-03 19:42 UTC, Adi-Amazon commented on Materials/decal/am_mud_decal.material
> +            "textureMap": "am_mud_decal.tif"
was the texture move to the root? why?

2021-12-03 19:42 UTC, Adi-Amazon commented on Materials/decal/scorch_01_decal.material
> +            "textureMap": "scorch_01_decal.tif"
moved to the root directory?

2021-12-03 19:44 UTC, Adi-Amazon requested changes
Not a blocker, but per my question - were the two textures moved to the root directory rather than Materials/decal?
This is not in this CR if so

2021-12-03 20:59 UTC, mrieggeramzn commented on Materials/decal/am_mud_decal.material
> +            "textureMap": "am_mud_decal.tif"
So I really just loaded, modified the alpha settings, and resaved. The material editor seemed to have made those changes. Also, I could reload that material afterwards (stopping and starting the materialeditor) and it seems to have worked ok. 

I just assumed the MaterialEditor knew more about paths than I did/

2021-12-03 21:47 UTC, Adi-Amazon approved these changes

2021-12-03 21:47 UTC, Adi-Amazon commented on Materials/decal/scorch_01_decal.material
> +            "textureMap": "scorch_01_decal.tif"
Assuming the editor work method started to look at local directory and remove the relative directory

2021-12-06 21:33 UTC, wintermute-motherbrain approved these changes

2021-12-06 21:33 UTC, merged